//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTC_Desktop.Responsity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemoryAction
    {
        public int ID { get; set; }
        public int ID_wallet { get; set; }
        public int ID_action { get; set; }
        public int Money { get; set; }
        public System.DateTime DateUse { get; set; }
    }
}
